services:
  oddstracker-postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: oddstracker-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-oddstracker}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE:-disable}
    # restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-oddstracker}",
        ]
      interval: 10s
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/data/postgres:/var/lib/postgresql/data
      # - ./src/schema/postgres.sql:/docker-entrypoint-initdb.d/schema.sql

  oddstracker-app:
    build: .
    container_name: oddstracker-app
    env_file:
      - .env
    environment:
      ROOT_DIR: /app
      POSTGRES_HOST: oddstracker-postgres
      POSTGRES_PORT: 5432
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    depends_on:
      oddstracker-postgres:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: oddstracker-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-clock-panel
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - oddstracker-postgres

volumes:
  postgres_data:
  grafana_data:
