apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: oddstracker-postgres:5432
    database: oddstracker
    user: ${POSTGRES_USER}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: true
    editable: true
